### ISSUE TITLE
反馈一个smb共享问题

### ISSUE THREAD

**Issue by orrinzeng** [sirpdboy/openwrt#257]
刷1214版（三个版）后，接上usb硬盘，通过电脑网上邻居可以正常访问硬盘的内容，但通过小米电视盒无法访问。提示“无法访问共享设备”。usb硬盘的格式是exfat。
另外，大全版运行一段时间后，无法通过WEB访问管理界面（风格是默认的）。

**Comment by orrinzeng** [comment]
共享问题是误报，在samba设置里，调整一下兼容设置就可以正常访问了。
无法通过WEB访问问题，只需要首次进入时，把界面风格设置成Bootstrap风格就行了。

**Comment by sirpdboy** [comment]
是的。没错，登陆路由器【SSH登陆】，运行下面命令即可：
curl -fsSL  https://raw.githubusercontent.com/sirpdboy/luci-theme-opentopd/master/luasrc/view/themes/opentopd/header.htm > /usr/lib/lua/luci/view/themes/opentopd/header.htm
