### ISSUE TITLE
Docker pull镜像报错

### ISSUE THREAD

**Issue by tcbywing** [sirpdboy/openwrt#260]
docker显示 Docker 根目录 /opt/docker (535.88 MB 可用)
但是pull镜像报错
code:200 failed to register layer: mkdir /opt/docker/vfs/dir/99a3a8da4794a356d0421fc9fe4d1f72bb7a53dc30977cde803d2278e402cc8c: no space left on device
请问如何解决？谢谢 补充一下 我pull的镜像30mb 剩余空间肯定够用

**Comment by sirpdboy** [comment]
路径要设置好。
