### ISSUE TITLE
iKoolProxy滤广告 插件任何屏蔽规则打开都会影响正常的网页访问

### ISSUE THREAD

**Issue by refined-fish** [sirpdboy/openwrt#279]
固件版本：OpenWrt Ipv6-S2022.01.15 by Sirpdboy / LuCI Master (git-21.335.48743-5f363d9)
不知道是不是我设置有问题，但是一打开广告屏蔽，规则勾选多或者少，都出现网页访问减缓（不正常的速度），并且有些正常网页会被拦截而无法访问

**Comment by sofs2005** [comment]
因为从115开始这个插件不支持运行了。。见我开的issue

**Comment by refined-fish** [comment]
哈哈，早知道先不换内核
