### ISSUE TITLE
更新建议：自带插件锐捷认证或许已经过时，可以考虑更新的minieap插件

### ISSUE THREAD

**Issue by refined-fish** [sirpdboy/openwrt#284]
在使用过程中尝试多次锐捷认证无一成功，查阅资料后得知这个旧版的锐捷认证仅支持锐捷认证V1,V2现在的校园网早已升级为v3,v4的认证，原插件不在生效，由此出现了新的认证插件minieap。
附上链接地址：https://github.com/updateing/minieap

**Comment by sirpdboy** [comment]
好的、这个以后更新上。

**Comment by refined-fish** [comment]
> 好的、这个以后更新上。

感谢回复
