### ISSUE TITLE
overlay分区被写爆了，导致某些插件配置不全无法使用

### ISSUE THREAD

**Issue by Delayless** [sirpdboy/openwrt#31]
![image](https://user-images.githubusercontent.com/42591058/96727089-428e6980-13e5-11eb-8dd8-fe2218c854bf.png)

现象如上图，`/etc/config/vssr`配置文件不完整，从中间截断，后半部分由于内存不足丢失了。
我没有额外安装任何插件，就是直接用您的固件，改改配置使用的，而且使用的插件也就那么五六个，并没有全部使用。
然后我用df查看了下磁盘情况，发现overlay完全满了，然后我进到/overlay目录用du查看了下已用空间只有200M，如图：
![image](https://user-images.githubusercontent.com/42591058/96727690-ef68e680-13e5-11eb-8df2-dbff691de874.png)

分析到这里，就不知道该怎么办了，望帮忙解决一下，谢谢您。

添加一条我的使用环境，我是直接用的img转vmdk在软路由使用的。

问题是找到了，是我的AdGuard Home的缓存我开了挺大，不过系统没有保护机制吗？比如开一部分保留内存只准系统使用？我记得桌面级的Linux发行版大部分都有保留部分内存的机制，openwrt应该也是可以开启的把。

**Comment by fsg1020** [comment]
我和你一样，碰到这个问题，开始了也没发现是AD造成的，现在每次关注/overlay使用，多了，就到AD中清理下。我挂载了一个分区，但貌似没成功。

**Comment by sirpdboy** [comment]
空间不够，可以扩展/overlay 。或者清除空间。

**Comment by Delayless** [comment]
> 空间不够，可以扩展/overlay 。或者清除空间。

嗯，不过我觉得可以在源码添加保护机制，不至于配置文件不完整导致插件不能用（我都是又建了一个虚拟机提取出原始配置文件才复原的）
