### ISSUE TITLE
安装后对未知域名的循环请求

### ISSUE THREAD

**Issue by bingoup886** [sirpdboy/openwrt#348]
<img width="653" alt="image" src="https://user-images.githubusercontent.com/20594548/172607183-c5128a0d-d393-48bb-aa56-92a9fd43202a.png">

发现路由器一致在请求该域名（aae-spweb.asuscloud.com），路由器中应该不存在asus相关的插件，能否去掉？

**Comment by sirpdboy** [comment]
这个不是软路由器来的，是你内网的华硕路由 发的请求访问 。。。
