### ISSUE TITLE
建议极致和精简增加微信推送插件

### ISSUE THREAD

**Issue by junke** [sirpdboy/openwrt#380]
建议极致和精简增加微信推送插件
另外请问我手动安装这个插件报错了，请问还有什么方法安装吗？

Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest. Not downgrading package luci-app-serverchan on root from git-22.174.45616-591316c to 2.01.4-9.

**Comment by sirpdboy** [comment]
用MINI版哦。

**Comment by junke** [comment]
> 

感谢，终于不用自己加包了
