### ISSUE TITLE
upnp插件bug

### ISSUE THREAD

**Issue by GFDCGFC** [sirpdboy/openwrt#393]
![image_2022-08-20_22-14-40](https://user-images.githubusercontent.com/96916244/185751059-d6d454af-b5af-4f68-bb4a-d25f831b1304.png)
要这样才能修复

**Comment by sirpdboy** [comment]
UPNP的这个问题是普遍现象？

**Comment by GFDCGFC** [comment]
是普遍现象，要按图片的操作才能正常
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年9月7日 10:31 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [sirpdboy/openwrt] upnp插件bug (Issue #393) |

UPNP的这个问题是普遍现象？

**Comment by sirpdboy** [comment]
这内容不太好修改，问题是你这修复的什么问题？ 现在用测试是没问题的哦。

**Comment by GFDCGFC** [comment]
修改UPNP插件配置文件
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年9月7日 13:38 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [sirpdboy/openwrt] upnp插件bug (Issue #393) |

这内容不太好修改，问题是你这修复的什么问题？ 现在用测试是没问题的哦。

**Comment by GFDCGFC** [comment]
不修改配置文件UPNP会开启失效
|
|
|


|
|


|
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年9月7日 13:38 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [sirpdboy/openwrt] upnp插件bug (Issue #393) |

这内容不太好修改，问题是你这修复的什么问题？ 现在用测试是没问题的哦。

**Comment by sirpdboy** [comment]
10.13号发了 升级upnp，加入外网接口和内网地址二个参数，并且自动设置。   你试试。
