### ISSUE TITLE
ipv6的bug

### ISSUE THREAD

**Issue by GFDCGFC** [sirpdboy/openwrt#394]
七八月份的固件都有这些bug，要么lan口不发ipv6，要么发了lan口不把流量发给wan口导致ipv6无效

**Comment by sirpdboy** [comment]
这是设置不对，删除WAN6。。一般就没问题了。

**Comment by GFDCGFC** [comment]
意思就是不用wan6也可以吗？删掉也行？



| |
龙猫
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年09月07日 10:29 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [sirpdboy/openwrt] ipv6的bug (Issue #394) |

这是设置不对，删除WAN6。。一般就没问题了。
