### ISSUE TITLE
ethtool: bad command line argument(s) 解决办法

### ISSUE THREAD

**Issue by yw0822** [sirpdboy/openwrt#395]
`Sat Aug 27 00:07:08 2022 daemon.err uhttpd[5557]: ethtool: bad command line argument(s)
Sat Aug 27 00:07:08 2022 daemon.err uhttpd[5557]: For more information run ethtool -h
Sat Aug 27 00:07:10 2022 daemon.err uhttpd[5557]: Device name longer than 15 characters`

vi /sbin/ethinfo
第五行改为
`for i in $(ip address | awk -F ': ' '/eth[0-9]+/ {print $2}' | awk '{ if ( length($0) <=4 ) print $0}' | xargs)`

**Comment by sirpdboy** [comment]
这个是 什么硬件 配置中出来的问题？

**Comment by sirpdboy** [comment]
这命令存在一定兼容性的话，下个版本换一下这个命令。。

**Comment by yw0822** [comment]
是启动docker的虚拟接口，名字超过15个字符了
