### ISSUE TITLE
实时监控没显示IP

### ISSUE THREAD

**Issue by bingoguo93** [sirpdboy/openwrt#399]
![图片](https://user-images.githubusercontent.com/37023599/188251240-eb266f81-f226-41d5-978e-1942268663dd.png)
没显示IP分辨不了哪个机器，不如下图流量统计的样式信息清晰
![图片](https://user-images.githubusercontent.com/37023599/188251261-6a19bad1-9067-42b0-9637-6a4ace86a3ce.png)

**Comment by sirpdboy** [comment]
嗯。有时间 给加一个IP在上面。
