### ISSUE TITLE
找不到socat这个软件的的入口

### ISSUE THREAD

**Issue by Balls98** [sirpdboy/openwrt#400]
找不到socat这个软件的的入口 能麻烦告知一下吗？ 谢谢

**Comment by Balls98** [comment]
是不是接口里面的那个端口转发  但是进去界面跟socat界面不一样 不会配置。。。。。

**Comment by sirpdboy** [comment]
和SOCAT差不多的。。

**Comment by a85559775** [comment]
> 和SOCAT差不多的。。

用不了，无法访问

**Comment by Balls98** [comment]
我需要V6转发 设置了 没反应 别的固件上的这个socat 配置了 可以 但是那个固件有点问题

**Comment by a85559775** [comment]
> 我需要V6转发 设置了 没反应 别的固件上的这个socat 配置了 可以 但是那个固件有点问题

我也是ipv6，无法访问。

**Comment by a85559775** [comment]
> 我需要V6转发 设置了 没反应 别的固件上的这个socat 配置了 可以 但是那个固件有点问题

我把这个home redirect卸载了，手动安装了socat，可以用了
