### ISSUE TITLE
实时监控出现未保存设置

### ISSUE THREAD

**Issue by bingoguo93** [sirpdboy/openwrt#401]
![图片](https://user-images.githubusercontent.com/37023599/188343455-78d172e2-8166-4fd3-9b04-848780feb7a5.png)
![图片](https://user-images.githubusercontent.com/37023599/188343475-79871526-e256-4c53-a14f-34b9e78ba018.png)

**Comment by sirpdboy** [comment]
这个是 监控的 设置值。默认应该是保存了。
