### ISSUE TITLE
mini版本

### ISSUE THREAD

**Issue by Maomaomgr** [sirpdboy/openwrt#409]
cpu的使用率和温度不准确 什么都没开 一直变来变去

**Comment by Maomaomgr** [comment]
温度有时候46度 过几秒就59度 再过几秒65度 然后又50度，幅度太大了吧

**Comment by Maomaomgr** [comment]
cpu占用率 也是 什么都没开 没测速 有时候40%多 过几天又7%然后30%几

**Comment by sirpdboy** [comment]
占用高，用HTOP查看是什么占用高。。查进程和资源使用情况 。
