### ISSUE TITLE
10.1版本的armv8貌似连zerotier都阉割了，nps frps也没有了

### ISSUE THREAD

**Issue by 5632515** [sirpdboy/openwrt#414]
感觉内网穿透有点少了，可以请求大大弄回来一点吗

**Comment by blacktea17** [comment]
zerotier没有了非常难受 用了很久只有换固件了

**Comment by 5632515** [comment]
看了电报说是mini版，但貌似挺久没更新armv8的高大全了

**Comment by 5632515** [comment]
> 下个版本会加回来。
万分期待，这么多固件版本用来用去，还是这里的少折腾，自己编译的没心思去整合别的代码仓库了，原本带的越来越少……而且编译上来稳定性成谜
