### ISSUE TITLE
大佬可以支持下fros插件吗？

### ISSUE THREAD

**Issue by jiecai58** [sirpdboy/openwrt#416]
<img width="808" alt="image" src="https://user-images.githubusercontent.com/26647044/197330074-8df1ebdb-a773-44ad-ae2b-a8fa8ec7f2b5.png">

**Comment by sirpdboy** [comment]
这插件没有哦。人家没开源的哦。

**Comment by jiecai58** [comment]
有个开源的 https://github.com/destan19/openfros2

**Comment by sirpdboy** [comment]
这个 应用过滤已经 新固件中 是有的了
