### ISSUE TITLE
更新建议： 内核缺少ipip tunnel模块，建议下一版编译进去

### ISSUE THREAD

**Issue by kx001001** [sirpdboy/openwrt#418]
内核缺少ip tunnel模块，建议下一版编译进去。创建ip2ip tunnel时分别报错如下， opkg 安装模块提示内核不匹配。

root@test: ip tunnel add ip2t mode ipip remote 1.1.1.1 local 1.1.1.2
**add tunnel "tunl0" failed: No such device**
root@test: ip tunnel add ip2t mode ipip6 remote fe80::22 local fe80::23
**add tunnel "ip6tnl0" failed: No such device**

root@test: opkg install ipip
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Installing ipip (4) to root...
Downloading https://mirrors.tencent.com/lede/snapshots/packages/x86_64/base/ipip_4_all.ipk
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.74-1-9f30f53bdba2722a473e0ebea48a1a77) for kmod-iptunnel
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.74-1-9f30f53bdba2722a473e0ebea48a1a77) for kmod-iptunnel4
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.74-1-9f30f53bdba2722a473e0ebea48a1a77) for kmod-ipip
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-ipip found, but incompatible with the architectures configured
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for ipip:
 *      kernel (= 5.15.74-1-9f30f53bdba2722a473e0ebea48a1a77)
 * opkg_install_cmd: Cannot install package ipip.

root@test: uname -a
Linux test 5.15.72 #0 SMP Wed Oct 12 15:49:44 2022 x86_64 GNU/Linux

**Comment by sirpdboy** [comment]
新版本有IPIP。。能不能用还要你自己试。
