### ISSUE TITLE
单主机如何实现双WAN线路主备切换

### ISSUE THREAD

**Issue by haodiao** [sirpdboy/openwrt#420]
我有一条线路是 电信 的，有一条是 CPE 的。    
平时主要使用 电信 的做为主出口，当电信的出现故障时，才会切换到 CPE 线路， 当 电信 恢复正常又自动切回来，也就是 CPE 平时几乎是处于不使用的备用状态。  

如何才能在单台 openwrt  上实现这样的功能， 
如果可以付费配置也行

**Comment by loso3000** [comment]
OEPNWRT上是可以 这么设置，但好像效果不是很理想。

**Comment by sirpdboy** [comment]
可以实现 ，效果可能不是很理想。
