### ISSUE TITLE
建议自动分配tf卡的剩余空间。

### ISSUE THREAD

**Issue by godamaranth** [sirpdboy/openwrt#424]
建议自动分配tf卡的剩余空间。

**Comment by sirpdboy** [comment]
TF卡的空间，这个要机器 来测试。 目前是做了LUCI的手动挂载分区格式化。

**Comment by GreenTeodoro839** [comment]
> TF卡的空间，这个要机器 来测试。 目前是做了LUCI的手动挂载分区格式化。

那个功能只能选整个外置磁盘，能不能让他使用系统盘的某个分区？要不64G卡浪费了

**Comment by sirpdboy** [comment]
之前 有这样弄过，大家反对。。就手动扩展 挂载了。
