### ISSUE TITLE
上网设备和上网内容管控APP

### ISSUE THREAD

**Issue by gh3007** [sirpdboy/openwrt#426]
能否开发手机APP，与openwrt里的家长控制，应用过滤，网络唤醒等功能匹配，在手机上可以远程控制上网设备和上网内容，方便对学生 上网进行管控；虽然手机也可以远程登录Openwrt进行管控设置，但是对于多数人，设置复杂，使用不方便，可以参考下图所示APP。可以作为功能增强的付费APP。

![微信图片_20221116131722](https://user-images.githubusercontent.com/85070937/202279080-af6d4ae3-6a24-4b7d-8e27-95e1bf6dc793.jpg)
![微信图片_20221116131710](https://user-images.githubusercontent.com/85070937/202279099-b5682f29-c10d-4afd-9142-7076267f6bc6.jpg)
![微信图片_20221116131718](https://user-images.githubusercontent.com/85070937/202279121-2e4d7e01-fcbe-4d53-9dc2-311e7181d4fd.jpg)

**Comment by loso3000** [comment]
开发这个是要建立 服务器，然后还要开发APP。。弄是可以弄。只是 成本有点高。。

**Comment by sirpdboy** [comment]
这个APP是可以做，只是成本有点高，要有人投资才行。。。
