### ISSUE TITLE
关于vip版的问题

### ISSUE THREAD

**Issue by azengjing** [sirpdboy/openwrt#427]
一直使用大佬的固件，更新快、稳定、功能多。一直心存感激。现在推出vip版，能获得更好的体验和服务，于情于理也是应该的。但一定要加入电报群才能获得吗？有没有其他更简单的方式推出？

**Comment by sirpdboy** [comment]
好伙伴的支持就是我们坚持走下去的动力！ 感谢支持！！目前TG是最安全少问题的哦，其他的都被管制，人数也有限制，QQ群容易被封。

**Comment by w4575421** [comment]
> 好伙伴的支持就是我们坚持走下去的动力！谢谢支持！！目前TG是最安全最小问题的哦，其他的都被管制，人数也有赦免，QQ群。

是直接扫GitHub上点赞赏码还是有另外点渠道加入 我也没有看到加入VIP的流程！！

**Comment by azengjing** [comment]
好伙伴的支持就是我们坚持走下去的动力！ 感谢支持！！目前TG是最安全少问题的哦，其他的都被管制，人数也有限制，QQ群容易被封。
--------------------------------------------------------------------------------------------------------------------------------------------
主要是很少用电报群，注册了好多次都不成功，原因是大陆手机收不到验证码。

**Comment by BiuZero** [comment]
> 

可以多试试，不同时间段可能有时候能收到
