### ISSUE TITLE
请问开启ipv6以后,微信或QQ接收图片很缓慢是什么原因?

### ISSUE THREAD

**Issue by 277383761** [sirpdboy/openwrt#439]
只要一开启ipv6,手机端的TIM也就是QQ加载图片就非常的缓慢,要转圈圈好几秒才能加载成功.关闭ipv6以后图片就可以秒加载了.
软路配置i5 8250u 16G内存 256G ssd 双千兆网口, pve里装的openwrt(楼主的固件)

**Comment by sirpdboy** [comment]
这个是 IPV6的DNS有问题。。
