### ISSUE TITLE
大佬，新内核的均衡插件好像有问题，lede那边貌似也是同样问题！

### ISSUE THREAD

**Issue by iovejieba** [sirpdboy/openwrt#442]
单线多拨，多线多拨，第一次配置的时候生效，负载均衡添加策略都无问题，重启后多拨报错，均衡显示每个虚拟wan口都没有默认路由表，lede那边现在也是一样的问题，感觉可能是新内核或者是均衡插件有不兼容问题，我想问问....在哪能下载历史固件.....我回滚下！

**Comment by sirpdboy** [comment]
有历史版本下载 。
