### ISSUE TITLE
希望添加上EasyMesh插件

### ISSUE THREAD

**Issue by cnfepa** [sirpdboy/openwrt#445]
相信广大网友也需求这个插件，MESH设备已经不少了。

**Comment by sirpdboy** [comment]
大全版VIP的已经加上 了

**Comment by cnfepa** [comment]
太好了点赞












土羊
***@***.***






---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月3日(周五) 中午1:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sirpdboy/openwrt] 希望添加上EasyMesh插件 (Issue #445)




 
大全版VIP的已经加上 了
