### ISSUE TITLE
dd命令烧写固件空间不足

### ISSUE THREAD

**Issue by allenzt** [sirpdboy/openwrt#448]
感谢博主发布的固件！我在看dd命令烧写固件时， 复制op.img到/tmp/tmp 但是按照现在的分区方案，放不下op.img 希望博主能调整下，感谢！！！

Disk /dev/sda: 29.82 GiB, 32017047552 bytes, 62533296 sectors
Disk model: Hoodisk SSD     
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 6186FB71-4653-D3B8-EFE7-1619579DF300

Device       Start     End Sectors  Size Type
/dev/sda1      512  131583  131072   64M Linux filesystem
/dev/sda2   131584 2025983 1894400  925M Linux filesystem
/dev/sda128     34     511     478  239K BIOS boot

~$ ls -lh ~/Downloads/op.img 
-rw-rw-r-- 1 dengzt dengzt 990M  1月  1 14:58 /home/dengzt/Downloads/op.img

**Comment by sirpdboy** [comment]
临时 文件TMP是内存虚拟的空间 空间不够。建议上传到 余下的硬盘分区。
