### ISSUE TITLE
建议添加kmod本地源

### ISSUE THREAD

**Issue by GreenTeodoro839** [sirpdboy/openwrt#451]
固件kernel md5和官方不一样，安装不了kmod模块。建议带一个kmod本地源或者编译时把md5改成官方的。
参考这个项目 https://github.com/SuLingGG/OpenWrt-Rpi
CONFIG_ALL_KMODS=y
CONFIG_ALL_NONSHARED=y

**Comment by sirpdboy** [comment]
这会增加固件体积。。可以定制 这种固件。

**Comment by GreenTeodoro839** [comment]
> 这会增加固件体积。。可以定制 这种固件。

不是本地软件源，kmod很小，一个只有几百k，不会占用很多空间
