### ISSUE TITLE
更新最新VIP大全版后网速测试功能不正常

### ISSUE THREAD

**Issue by weili888** [sirpdboy/openwrt#453]
刚刚更新20230121-Ipv6-Plus-Vip-6.1大全版后使用网络测速功能中的Speedtest宽带测速功能，测速完毕后正常应该显示一个测试结果图片，但是此图片不能正常显示。请问这个是什么问题？
![OpenWrt - Speedtest宽带测](https://user-images.githubusercontent.com/48369706/213913259-0a49d92f-1757-4ddf-9f19-d80c5cfad354.png)

**Comment by sirpdboy** [comment]
这可能是图片显示出问题了。 不影响 。

**Comment by sirpdboy** [comment]
新版本已经解决这个问题了。
