### ISSUE TITLE
虚拟机平台无CPU温度传感器导致日志刷屏

### ISSUE THREAD

**Issue by Primimy** [sirpdboy/openwrt#454]
**版本**：OpenWrt Ipv6-Plus-Vip-R2023.01.21
**问题**：在Esxi虚拟机平台上无法读取到CPU温度，访问后台会导致日志中一直显示报错
![image](https://user-images.githubusercontent.com/38491737/214008068-92e0d345-0141-4545-8320-dc7ef10a6573.png)
测试为命令“sysinfo tempinfo”导致
![image](https://user-images.githubusercontent.com/38491737/214009063-ee1cd5fb-f7b0-49f4-825a-e122950bb40a.png)
**暂缓的办法**：修改/usr/lib/lua/luci/view/admin_status/index.html,line 74为
local cpu_wd ="+0°C"
![image](https://user-images.githubusercontent.com/38491737/214009513-989a082d-161f-4ed3-bee0-c62461eb10da.png)
有没有其他办法解决这个问题，因为更新后需要重新改

**Comment by sirpdboy** [comment]
好，下个版本测试 查问题。

**Comment by sirpdboy** [comment]
新版本已经解决。
