### ISSUE TITLE
X86版本，多个版本均有物理网口与逻辑网口不能稳定保持对应关系的问题

### ISSUE THREAD

**Issue by sxlive** [sirpdboy/openwrt#461]
从去年10月1日以后版本之后（不包括10月1日的版本），包括2023年3月1日的版本，多个不同时间的版本均出现一个bug。
就是重启路由后物理网口与ETH？的对应关系可能发生变化，暂时没发现规律。假设ETH0默认为第一个物理网口，ETH1为第二个物理网口……，重启虚拟机后，这种绑定关系有一定概率发生变化，并且暂未发现明显规律。
系统软件平台：WIN2022 +HYPERV虚拟机；硬件平台为畅旺多个版本4网口小主机及4口NAS主板。4个网口直通3个给虚拟机。
猜测是固件问题，因为22年10月1日的版本并无该问题。

**Comment by sirpdboy** [comment]
测试 是没问题，如果虚拟机有变化， 虚拟机中 物理口绑定变化了就会影响 。
