### ISSUE TITLE
r4s开启gpu

### ISSUE THREAD

**Issue by GreenTeodoro839** [sirpdboy/openwrt#462]
依赖冲突，Close

能否编译上r4s的gpu驱动？用这些kmod就可以
骷颅头那边出现了依赖冲突编译失败，如果这里也不行就算了
> 开启GPU硬件

```CONFIG_PACKAGE_kmod-backlight=y`
CONFIG_PACKAGE_kmod-drm=y
CONFIG_PACKAGE_kmod-drm-kms-helper=y
CONFIG_PACKAGE_kmod-drm-rockchip=y
CONFIG_PACKAGE_kmod-fb=y
CONFIG_PACKAGE_kmod-fb-cfb-copyarea=y
CONFIG_PACKAGE_kmod-fb-cfb-fillrect=y
CONFIG_PACKAGE_kmod-fb-cfb-imgblt=y
CONFIG_PACKAGE_kmod-fb-sys-fops=y
CONFIG_PACKAGE_kmod-fb-sys-ram=y
CONFIG_PACKAGE_kmod-gpu-lima=y
CONFIG_PACKAGE_kmod-multimedia-input=y
CONFIG_PACKAGE_kmod-video-core=y```

**Comment by sirpdboy** [comment]
好 下一版加上试试

**Comment by GreenTeodoro839** [comment]
> 好 下一版加上试试

新版固件好像又没了，另外r4s感觉内核5.4.188很稳定，能不能用这个内核编译
